### ISSUE TITLE
I can't find a licence file anywhere

### ISSUE THREAD

**Issue by richard-delorenzi** [volca/markdown-preview#103]
I checked here and on the chrome store, but can not find the licence.
see https://help.github.com/en/articles/licensing-a-repository

**Comment by volca** [comment]
I forked the repo from Boris's repo and I have made many changes already. I checked his repo but no license file also.  Maybe I should write issue to him.

**Comment by cxw42** [comment]
@volca Yes, please!  Besides the code, I would also like to know the license for the theme CSS files.

This is a great extension!  Many thanks, and keep up the good work!

**Comment by cxw42** [comment]
Thank you!
