### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by mikezhang95** [volca/markdown-preview#104]
Excuse me, I'd like to know how to change the image size during display ?

**Comment by volca** [comment]
see [this link](https://gist.github.com/uupaa/f77d2bcf4dc7a294d109). is is helpful?

**Comment by volca** [comment]
I will close the issue. Reopen it if you need

**Comment by aky100200** [comment]
Nice to meet you. 

Hey, volca.

Thank you for making a great feature.

I also want to resize the image.
However, I checked the above link and tried it, but the resizing was not recognized.

I tried the following.
* ![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png | width=100)
* ![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png =250x250)
* \<img src="url" alt="alt text" width="whatever" height="whatever">

What if I could use the following syntax according to github?

```
<img src="./image/sample1.png" width="300px">
```

Thank you. We are looking forward to hearing from you.

**Comment by volca** [comment]
You can enable "HTML content" in the options page of Markdown Preview Plus

**Comment by aky100200** [comment]
@volca 
Thank you for your prompt reply.

>You can enable "HTML content" in the options page of Markdown Preview Plus

After enabling the option, I was able to see it.

Thank you very much.
