### ISSUE TITLE
Is it possible to add the mermaid?

### ISSUE THREAD

**Issue by ioOiOiOoi** [volca/markdown-preview#106]
mermaid: https://github.com/knsv/mermaid

I want to render the mermaid in a markdown document.

I opened the **manifest.json** file, then added `"js/mermaid.min.js"` to `"js": []`. 

Next, how can I use mermaid? Thank you!

**Comment by volca** [comment]
You can the function [makeHtml](https://github.com/volca/markdown-preview/blob/master/js/markdownify.js#L43) and try to add render function for mermaid in it. 

I'm busy recently and can't pay more time on this. Sorry.

**Comment by ioOiOiOoi** [comment]
@volca OK, Thank you!

**Comment by volca** [comment]
see https://github.com/volca/markdown-preview/pull/111
