### ISSUE TITLE
Support for math syntax of GitLab

### ISSUE THREAD

**Issue by s417-lama** [volca/markdown-preview#107]
In GitLab markdown, the following math syntax is supported.

Inline:
`` $`a^2+b^2=c^2`$ ``

Block:
````
```math
a^2+b^2=c^2
```
````

Reference: https://docs.gitlab.com/ee/user/markdown.html#math

How about supporting them?

**Comment by volca** [comment]
please check the option page for markdown preview plus. enable the option "KaTeX support" first.

Let me know if this works for you

**Comment by s417-lama** [comment]
Thank you for your reply.

I know the KaTeX support works, but I want the GitLab syntax for math (`` $` `` and `` `$ ``) for interoperability between this plugin and GitLab.

**Comment by volca** [comment]
I think we will not enable "GitHub Flavored Markdown" and "Gitlab" syntax in same time.

**Comment by s417-lama** [comment]
The currently supported math syntax (`$...$` and others) is not a part of "GitHub Flavored Markdown" in the first place.
I guess supporting `` $` `` and `` `$ `` is not a problem, either.

**Comment by volca** [comment]
It's KaTex extension. Someone added a [pull request](https://github.com/volca/markdown-preview/pull/91) for the feature.

You can also try to submit a pull request if you need the Gitlab syntax.

**Comment by volca** [comment]
merged. Reopen the issue if you need
