### ISSUE TITLE
Request: permit manually specifying highlighting language in Markdown fenced blocks

### ISSUE THREAD

**Issue by cxw42** [volca/markdown-preview#113]
Thank you for this extension, which is very useful!  I would like to be able to manually specify the highlighting language so that I can un-highlight plain text blocks.  For example, I am seeing highlighting in `ls -l ; sha256sum` output:

![image](https://user-images.githubusercontent.com/10515894/93091971-cfb70380-f66c-11ea-96e4-85c3f6e5a11f.png)

As far as I can tell, only automatic language detection is currently supported:

https://github.com/volca/markdown-preview/blob/8b0d0293a219d07a7b06fb397fc4c8e4e51b6e40/js/config.js#L12-L14

I see from its docs that highlightjs can take a language parameter using [`highlight()`](https://highlightjs.readthedocs.io/en/latest/api.html#highlight-languagename-code-ignore-illegals-continuation).  I would like Markdown Preview Plus to read the language tags from fenced code blocks such as below, and pass those language tags to `highlight()`.

    ```text
    -rw-r--r-- 1 root root ...
    ````

(with the `text` tag)

I may be able to work on this if you are not able to, but would certainly appreciate any advice you could provide!  Much appreciated!

**Comment by volca** [comment]
Please update to v0.7.9 after hours

**Comment by cxw42** [comment]
Thank you very much for your quick response!  I see that 0.7.10 is out.  I'll give it a try!
