### ISSUE TITLE
<code> tag not work

### ISSUE THREAD

**Issue by KnIfER** [volca/markdown-preview#117]
![image](https://user-images.githubusercontent.com/11593903/95724687-3d287500-0ca9-11eb-83fd-fbce04622792.png)

自己项目的md都不能正确渲染。。。

**Comment by KnIfER** [comment]
![image (1)](https://user-images.githubusercontent.com/11593903/95730282-9ea01200-0cb0-11eb-80aa-664b7c995497.png)

搞定……

**Comment by volca** [comment]
try with markdown syntax instead


\`\`\`$math$
your codes...
blah blah....
\`\`\`

**Comment by KnIfER** [comment]
blah blah. Not Inline !!!
