### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by KnIfER** [volca/markdown-preview#118]
甘特图竖线浓淡不均（BUG）
流程图颜色过于鲜艳
sequenceDiagram 字体过浓，显得模糊

![image (3)](https://user-images.githubusercontent.com/11593903/96082559-02634e80-0eee-11eb-993e-299ce597613a.png)

**Comment by KnIfER** [comment]
表格没有样式

**Comment by volca** [comment]
这里使用到了[flowchart.js](http://flowchart.js.org/). 暂时不会对它的样式做改动

**Comment by volca** [comment]
请问你指的表格是[这种](https://github.com/volca/markdown-preview/blob/master/test/test_gfm.markdown)吗

**Comment by KnIfER** [comment]
是，默认样式没有它，我直接抄csdn的。

**Comment by KnIfER** [comment]
解决了啊？

**Comment by volca** [comment]
不解决了，你可以尝试上传并设置自己定义的样式表
