### ISSUE TITLE
[Feature Request] Mermaid.js Update

### ISSUE THREAD

**Issue by KSR-Yasuda** [volca/markdown-preview#129]
Could you update Mermaid.js to the latest ver.?

Current ver. looks v8.7.0; The latest is v8.13.10.

On the current version,
some of complex mermaid syntax looks unsupported.

**Comment by KSR-Yasuda** [comment]
For example, the current ver. does not understand `class` syntax.

### Sample

```mermaid
flowchart LR

subgraph Sub1
    A --> B
end

subgraph Sub2
    C --> D
end

B & D --> E --> F

classDef Colored stroke-width:3px,fill:#F99,stroke:#C33
class B,D Colored
```

### Expected

![Expected](https://user-images.githubusercontent.com/31273423/151130732-d98c62d3-4f5e-4a3c-a148-4f89c7d13871.png)

### Current

![Current](https://user-images.githubusercontent.com/31273423/151130738-f903d26e-f9d1-4e4c-b09e-89cf15dbafa9.png)

----

With `class` syntax, in some cases, it can go wrong to fall into syntax error  
(I'm not sure especially what code causes error, though.  
It would be complicated with `class` syntax forcible interpretation, node naming, etc.).

**Comment by volca** [comment]
Will update mermaid.js in v0.7.18
