### ISSUE TITLE
Get garbled in non-UTF8 file

### ISSUE THREAD

**Issue by KSR-Yasuda** [volca/markdown-preview#141]
It gets garbled on non-UTF8 files.

For example, the document below is written in charset EUC-JP.

* <https://i-red.info/docs/jfp/usbmon.txt>

Without MarkdownPreviewPlus, it is displayed in EUC-JP correctly.

With MarkdownPreviewPlus enabled,
it styles the document in the file encode EUC-JP at first.

![MarkdownPreview_20230310_164416](https://user-images.githubusercontent.com/31273423/224257382-724c124d-77cf-40ba-9360-9dc242707af3.png)

However, after a while, it wrongly changes charset to UTF-8.

![MarkdownPreview_20230310_164423](https://user-images.githubusercontent.com/31273423/224257389-819f8904-d15d-493e-886f-be19692fb6fa.png)

Environment
--------------------------------------------------------------------------------

* Markdown Preview Plus v0.7.24
* Chrome 111.0.5563.65 (Official Build) （64 bits） (cohort: 111_Win_64_Ramup)
* Windows 10 Pro 22H2 (Version 10.0.19045.2604)

**Comment by volca** [comment]
The page doesn't send encoding in the response header. the header is 

```
content-type: text/plain
```

e.g. it should contains the charset part 

```
Content-Type: text/html; charset=utf-8
```
