### ISSUE TITLE
Feature Request: using custom mermaidjs files

### ISSUE THREAD

**Issue by ta946** [volca/markdown-preview#142]
is it possible to add functionality to link a mermaidjs file (and inturn choose version) to use for rendering?
I'm using the latest mermaidjs (v10) locally to write the md, and use this plugin for viewing online, but since the mermaid version is 9.4, some new functionalty breaks the graph

Would be nice to be able to choose the file to avoid waiting for an update, or to render with an older version (for whatever reason) especially since they seem to be pushing major changes often recently

**Comment by volca** [comment]
Mermaidjs v10 is ESM only. it dropped CJS support. Can we add ESM module to chrome extension?

**Comment by ta946** [comment]
I've never written a chrome extension so I'm not sure im even searching the right path
https://medium.com/front-end-weekly/es6-modules-in-chrome-extensions-an-introduction-313b3fce955b
this mentions es6 support in chrome extensions, theres also an [update] section about content scripts which links to this [stackoverflow](https://stackoverflow.com/questions/48104433/how-to-import-es6-modules-in-content-script-for-chrome-extension/48121629#48121629)

Now that i think about it, idk if manifest v3 will allow a custom js file since you have to declare things beforehand in the manifest

I thought it might be an easy thing to add since you'd added the functionality to use a custom css file. But if its not then understandable if its too much work

**Comment by volca** [comment]
Closed. see #144
