### ISSUE TITLE
C code is not highlighted

### ISSUE THREAD

**Issue by KSR-Yasuda** [volca/markdown-preview#143]
Code block of `c` is not syntax highlighted.

Couldn't you enable the language name `c`?

### Code

~~~markdown
```c
// c: [NG] Not highlighted
int main(int argc, char *argv[]) {
    return 0;
}
```

```cpp
// cpp: [OK] Highlited
int main(int argc, char *argv[]) {
    return 0;
}
```

```c++
// c++: [OK] Highlited
int main(int argc, char *argv[]) {
    return 0;
}
```
~~~

### Preview

![C_Highlight_20230519_181858](https://github.com/volca/markdown-preview/assets/31273423/03d1fca6-6929-4271-9514-ff16ee2a626e)

Version
--------------------------------------------------------------------------------

* Markdown Preview Plus v0.7.24

**Comment by volca** [comment]
I've pushed a new package for the bug. Please wait days.

**Comment by KSR-Yasuda** [comment]
Now I checked v0.8.0 works fine.

**Comment by volca** [comment]
Thanks for confirming that
