### ISSUE TITLE
span tags showing in code blocks

### ISSUE THREAD

**Issue by Kernix13** [volca/markdown-preview#150]
My markdown files show the correct language syntax highlighting for a few seconds then the code blocks change to showing the span tags used to create the code blocks. 

Correct view:

<img width="632" alt="image" src="https://github.com/volca/markdown-preview/assets/66497948/350ed04a-34a8-493a-8bbe-11370496b9f1">

View after a few seconds:

<img width="743" alt="image" src="https://github.com/volca/markdown-preview/assets/66497948/88195e84-e816-4b15-b84b-c6b1c4f7831f">

What was changed to make this happen? Have you checked your own markdown files?

**Comment by volca** [comment]
I will try to re-produce the issue first

**Comment by volca** [comment]
I pushed a new package. Please wait days
