### ISSUE TITLE
MarkedJs breaking API change are unaddressed, rendering fails.

### ISSUE THREAD

**Issue by zvodd** [volca/markdown-preview#155]
Viewing a markdown file shows a mostly unformatted text.
`markdownify.js:L106`
```
TypeError: marked.Slugger is not a constructor
```

You can see in the MarkedJs repo at some point before commit `f45cfc3e2d6082736e7835862cc6deb911218633` the Slugger part of the API has changed.

https://github.com/markedjs/marked/compare/ccc7a8fb3427152d11d24720847c19f355d27e8d...f45cfc3e2d6082736e7835862cc6deb911218633  - click on "Files Changes" to view diff and search Slugger and you can see many deleted lines.

Dug a little deeper and found:
https://github.com/markedjs/marked/pull/2984

Looks like they have removed that from version 8 or 9 of MarkedJs, so solution is probably either: reverting MarkedJs to an earlier version, or to reimplement and probably use [github-slugger](https://www.npmjs.com/package/github-slugger) instead as they recommend.

**Comment by volca** [comment]
Thanks for note. I will look into this later

**Comment by volca** [comment]
github-slugger is a esm package. It can't work proper with the plugin. So I downgrade marked instead.
