### ISSUE TITLE
Mermaid: `<br>` line breaks are dropped

### ISSUE THREAD

**Issue by KSR-Yasuda** [volca/markdown-preview#158]
In some part, Mermaid graph allows line breaking with `<br>` tag,
however, this plugin drops them.

### Target Graph Code

```text
%%{ init : { "theme" : "default" }}%%

flowchart LR

a[NodeA]
b[NodeB:<br>with line break]

a --> b
```

### Plugin Rendering (NG)

![Mermaid_NG_20241125_110837](https://github.com/user-attachments/assets/079d5c9a-f9d3-43b2-828a-405b41833507)

### Expected Rendering (OK)

![Mermaid_OK_20241125_110842](https://github.com/user-attachments/assets/9f87e1ef-365d-4f9f-8701-3c739c0e588b)

**Comment by volca** [comment]
Thanks for good describe the bug. I will check later.
