### ISSUE TITLE
If it contains a code highlight part, The page will scroll to top when auto-reload. (自动刷新会滚动到页面顶部)

### ISSUE THREAD

**Issue by Zzway** [volca/markdown-preview#16]
能否在刷新后停留在原来位置？

或者提供一种快速开关自动刷新功能的方式

**Comment by volca** [comment]
有种方式是在光标处插入隐藏的html标记，用于刷新跳转，但是我实测效果并不好。我会抽空看看有没有更好的解决办法

**Comment by volca** [comment]
今天测试刷新可以停留在原处，请问你这个情况如何重现

**Comment by volca** [comment]
测试发现，当页面中有代码片段code的时候，高亮部分的代码导致页面滚动到顶部

**Comment by volca** [comment]
see #22 The page will scroll to top if it contains a code highlight part.

**Comment by volca** [comment]
rollback to v0.4.1 to fix the issue
