### ISSUE TITLE
only support the css the size less than 4k.

### ISSUE THREAD

**Issue by volca** [volca/markdown-preview#19]
4KB is too small, 8KB maybe better.

From Chrome Extension Dashboard

**Comment by edwardmcham** [comment]
8 kb is also too small. I discovered the custom CSS file feature a few minutes ago and tried to upload mine. Even when minified, it's 23 kb.

Also, can I add more than one custom CSS file? The other two are only 1-2 kb each. All 3 CSS files are on my local drive. Thanks!

**Comment by volca** [comment]
The custom css is stored in the lcoalStorage and the maximum size of per item is 8kB.

I will check how to link to your local CSS files instead.

**Comment by volca** [comment]
I will add a textarea directly. You can input the paths of your own css files.

![Screenshot 2024-11-22 at 09 35 12](https://github.com/user-attachments/assets/99d4291c-0cef-4c18-a04f-495ca50452ef)

**Comment by volca** [comment]
You can input your css path like this

```
https://github.githubassets.com/assets/primer-af846850481e.css
file:///Users/abc/my-great-theme/MyAnotherGithub.css
```

The extension will add css to the page

```
<link class="CUSTOM_CSS_PATH" rel="stylesheet" href="https://github.githubassets.com/assets/primer-af846850481e.css">
<link class="CUSTOM_CSS_PATH" rel="stylesheet" href="file:///Users/abc/my-great-theme/MyAnotherGithub.css
">
```

The priority of custom css path is higher than the built-in theme css.
