### ISSUE TITLE
UTF-8 files incorrectly displayed

### ISSUE THREAD

**Issue by ezuk** [volca/markdown-preview#2]
The extension renders UTF-8 files with incorrect encoding, even if they start with `<meta charset=utf-8">`. Manually changing the encoding in Chrome works, but it's a hassle.

**Comment by smallwalk** [comment]
Chinese garbled

**Comment by volca** [comment]
@smallwalk  Did you check the option "Enable auto-reload"?

**Comment by smallwalk** [comment]
@volca, I have checked the option "Enable auto-reload"。I changed the browser's default charset to solve the problem.

**Comment by volca** [comment]
It will show correct encoding after first reload if you have chosen right encoding in Chrome.

**Comment by volca** [comment]
see #42 also
