### ISSUE TITLE
Math equations will not be rendered after page auto-reload

### ISSUE THREAD

**Issue by chaserhkj** [volca/markdown-preview#20]
This is due to that page auto-reloading is done by ajax and MathJax would only search for equations and renders them after page load.

According to [this](http://docs.mathjax.org/en/latest/typeset.html) documentation of MathJax, reload of MathJax could be triggered by calling
```javascript
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
```
in the page context. However, I didn't find an elegant enough way to do this in content scripts, I'll get to this issue later.

**Comment by volca** [comment]
Here's another tool has the feature auto render MathJax. I will look into it.

http://markx.herokuapp.com/
