### ISSUE TITLE
MathJax not working on 0.4.3

### ISSUE THREAD

**Issue by chaserhkj** [volca/markdown-preview#23]
On Linux chrome environment, it reports
```
File failed to load: chrome-extension://fijgjjkgmbbabogmmgnngonionmgpbgl/js/jax/output/HTML-CSS/fonts/TeX/fontdata.js
```

Seems that it's due to the lack of corresponding MathJax data file.

I recommend that:
- Use the MathJax CDN other than locally provide MathJax files to render, like I've done in #18 
- Include all relating MathJax data file(`jax/input/Tex`, `jax/output/HTML-CSS/fonts`) to extension

Note that fonts used by MathJax seems to be different from platform to platform, since some platform may have built-in math fonts that is available to use. (Note this:`jax/output/HTML-CSS/fonts/TeX/WinChrome`) Because of this add-and-try method may not be working since only the testing platform is covered. We should whether include all related data files, or refer to MathJax manual and ask MathJax developers to find out how to clean up MathJax data files that are not used.

I may look into this myself later.

Happy hacking,
Chaserhkj.

**Comment by volca** [comment]
I agree with your point. 

I have tested some simple MathJax. I hope the extension can work when it's offline. But the MathJax depend on so many other files.
