### ISSUE TITLE
Auto-reload clears text selection

### ISSUE THREAD

**Issue by broofa** [volca/markdown-preview#24]
1. Make sure `Enable auto-reload` checkbox is checked
  2. Open MarkDown document
  3. Use mouse to select (highlight) text
  4. Wait a few seconds... **text selection is cleared**

This is an issue with both `file:` and `http:` URLs.

Expected behavior: Page should only refresh if the underlying document has actually changed.

**Comment by volca** [comment]
Got it. I will check it.

**Comment by broofa** [comment]
Thanks!
:dancers:
