### ISSUE TITLE
Feature request: embed css when using "Export to HTML"

### ISSUE THREAD

**Issue by nzbart** [volca/markdown-preview#25]
It would be nice if the html file generated by the Export to HTML feature could be opened in browsers other than Chrome, and by users who do not have the Markdown Preview Plus extension installed.

Unfortunately, the CSS file is linked like this:

```html
<link rel="stylesheet" id="theme" href="chrome-extension://febilkbfcbhebfnokafefeacimjdckgl/theme/Clearness.css">
```

This means that anyone not using Chrome with Markdown Preview Plus will see the exported file without any styles, which looks pretty basic.

**Comment by volca** [comment]
The version v0.4.6 will export mhtml file.
