### ISSUE TITLE
new permissions requested

### ISSUE THREAD

**Issue by justinmk** [volca/markdown-preview#26]
Recently Chrome reported that the plugin requires new permissions:

> Read and change all your data on the websites you visit

> Manage your downloads

[Chrome documentation](https://developer.chrome.com/extensions/permission_warnings#warnings) suggests this could be avoided:

> Note that you may be able to avoid declaring all host permissions using the **activeTab** permission.

Thanks for the plugin!

**Comment by volca** [comment]
Thanks for your remind! I will give it a try.

**Comment by volca** [comment]
see #28
