### ISSUE TITLE
Exporting to HTML fails on Google Chrome version 45.0.2454.85 m

### ISSUE THREAD

**Issue by eriknstr** [volca/markdown-preview#28]
>export.mhtml may harm your browsing experience, so Chrome has blocked it.

The only options are *dismiss* and *[learn more](https://support.google.com/chrome/answer/6261569?p=ib_download_blocked&hl=en&rd=1)*.

**Comment by volca** [comment]
Thank you for your reminder. I will check it.

**Comment by volca** [comment]
Does the issue repeat with new chrome version? I tested with 51.0.2704.103 and it's ok.

**Comment by eriknstr** [comment]
Export for HTML works for me as well now. Currently using Chromium version 51.0.2704.63.

**Comment by volca** [comment]
Thanks for confirming that
