### ISSUE TITLE
local file with protocol file:/// not rendered

### ISSUE THREAD

**Issue by KingMario** [volca/markdown-preview#29]
the Mac OS X Chrom version 46.0.2490.71 (64-bit)

**Comment by volca** [comment]
Did you check the option "Allow access to file URLs" in chrome://extensions listing?

**Comment by KingMario** [comment]
The option is checked. But the protocol header of local file opened is *file:///* (with **THREE** slashes). Does this matter?

**Comment by volca** [comment]
I just upgrade my Chrome to 46.0.2490.71 (64-bit) on OS X. It works well.

What extension is the markdown file?

**Comment by KingMario** [comment]
My fault, I didn't check the option in chrome://extensions, but only the file://*/*.md in MackDown Viewer Plus options.
But the Chinese characters are displayed in a mess, and the encoding is not selectable.

**Comment by volca** [comment]
You can choose the encoding in chrome menu -> "View" -> "Encoding".  ( 视图 -> 编码 )

**Comment by KingMario** [comment]
For the file with Chinese characters, the GBK encoding is selected automatically, but the page is in a mess, and all the encoding options are all greyed for the local file.
For a remote file (http://...), the encoding options are enabled, and the default UTF-8 encoding is selected for the same file.

**Comment by KingMario** [comment]
From the inspector of Chrome developer's tool, I can read the *source* of the converted html. And the content is not manipulated properly.

The [MarkDown Viewer](https://chrome.google.com/webstore/detail/markdown-viewer/ehnambpmkdhopilaccgfmojilolcglhn) converts my H1 into:

    <h1 id="0">云尚读片平台</h1>

But MarkDown Preview Plus converts it into:

    <h1 id="-">浜戝皻璇荤墖骞冲彴</h1>

The good thing about MarkDown is that it generates a table of contents. But it can't deal with MarkDown tables.
