### ISSUE TITLE
Chinese in exported html unreadable

### ISSUE THREAD

**Issue by mzlogin** [volca/markdown-preview#30]
If I have a markdown file in Chinese like this:

```
# 这是一个测试文件

### 标题一

一些内容在这里
```

and the exported mhtml file's body is like this:

```
<body><h1 id=3D"-=
">=E8=BF=99=E6=98=AF=E4=B8=80=E4=B8=AA=E6=B5=8B=E8=AF=95=E6=96=87=E4=BB=B6<=
/h1>
<h3 id=3D"-">=E6=A0=87=E9=A2=98=E4=B8=80</h3>
<p>=E4=B8=80=E4=BA=9B=E5=86=85=E5=AE=B9=E5=9C=A8=E8=BF=99=E9=87=8C</p>
</body>
```

It's unreadable, how can I export a html file with Chinese in the source show normally?

**Comment by volca** [comment]
Did you change the encoding to UTF-8?

**Comment by mzlogin** [comment]
I have tried UTF-8, GBK and gb18030 encoding, the `<body>` is all unreadable.

![markdown-preview-plus](https://cloud.githubusercontent.com/assets/1646590/11292810/09de02a2-8f8e-11e5-9727-3a45b37a8aec.png)

**Comment by volca** [comment]
The text have encoded as [Quoted-printable](https://en.wikipedia.org/wiki/Quoted-printable) format. You can check the wiki for more detail.

**Comment by mzlogin** [comment]
Yes, I've searched `mhtml` and `quoted-printable`, it seems all mhtml files' `Content-Transfer-Encoding` is `quoted-printable`.

So there is no way to solve this issue as of now?

If so, could you add an option to decide whether export `embedded css html` or `mhtml`? I noticed that the earlier version of this extension export html.

**Comment by volca** [comment]
the html format can't support image and stylesheet correctly
