### ISSUE TITLE
MathJax script is causing browser security warning

### ISSUE THREAD

**Issue by blueacorn** [volca/markdown-preview#33]
The MathJax script is attempting to access a remote .js script

jquery.js:8336 Mixed Content: The page at 'https://****.internal.server/svn/trunk/README.md' was loaded over HTTPS, but requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML&_=1465577108526'. This request has been blocked; the content must be served over HTTPS.send @ jquery.js:8336

Any Markdown file viewed over https:// causes this security warning in Chrome.

Plugin should not be allow execution of remote javascript anyway?!

**Comment by volca** [comment]
see #37
