### ISSUE TITLE
Does not support - [x] checkboxes

### ISSUE THREAD

**Issue by jpouellet** [volca/markdown-preview#34]
The features list says it supports github flavored markdown, but this file:

```
foo:
====
- [ ] abc
- [x] def
```

produces this on github:
![2016-06-28-010837_149x134_scrot](https://cloud.githubusercontent.com/assets/1231207/16404469/4171511e-3ccd-11e6-8d89-36504e6cc08f.png)

and this in the plugin:
![2016-06-28-010904_113x107_scrot](https://cloud.githubusercontent.com/assets/1231207/16404473/48ac8f16-3ccd-11e6-82f4-a7c949af9309.png)

**Comment by volca** [comment]
see https://github.com/chjj/marked/pull/587

I'm waiting for the merge

**Comment by dariober** [comment]
Hi- Is there any update about this? I would also like this feature enabled. Thanks!

**Comment by volca** [comment]
Please vote at chjj/marked#587 if you like the feature

**Comment by jpouellet** [comment]
Thanks!
