### ISSUE TITLE
not rendering github flavored anchors

### ISSUE THREAD

**Issue by dkebler** [volca/markdown-preview#35]
Despite choosing github flavored your render code is not rendering anchors per the below so viewing something offline like a large single page documentation of an api like [this](https://github.com/cujojs/when/blob/master/docs/api.md) one is pretty impractical.

> The code that creates the anchors is here:
> https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb
> 
> It downcases the string
> remove anything that is not a letter, number, space or hyphen (see the source for how Unicode is handled)
> changes any space to a hyphen.
> If that is not unique, add "-1", "-2", "-3",... to make it unique

**Comment by volca** [comment]
see #38
