### ISSUE TITLE
Add support for Markdown Extra Definition lists: 

### ISSUE THREAD

**Issue by blueacorn** [volca/markdown-preview#36]
Add support for Markdown Extra Definition lists:
https://michelf.ca/projects/php-markdown/extra/#def-list

>     term
>     :     Definition and description text

Becomes:
**term**
`        ``    `Definition and description text with html \<dl\> tags

**Comment by volca** [comment]
Your best bet is to implement it (or request its implementation) in the rendering library that Markdown Preview Plus uses: [Marked](https://github.com/chjj/marked).

Here are a issue you could follow on: https://github.com/chjj/marked/issues/27
