### ISSUE TITLE
don't support latin characters

### ISSUE THREAD

**Issue by ivanchodelat** [volca/markdown-preview#42]
in .md file: 
ñ Ñ á é í ó ú 
on brouser:
Ã± Ã‘ Ã¡ Ã© Ã­ Ã³ Ãº

**Comment by volca** [comment]
Please change the file encoding to utf-8 first. You will see nice latin characters. Here's [an example](https://raw.githubusercontent.com/volca/markdown-preview/3180b69a593a12bf3538c149d040e7db835549ce/test/test_latin.markdown).

**Comment by ivanchodelat** [comment]
thanks, all is right.
