### ISSUE TITLE
single # not supported on github mode

### ISSUE THREAD

**Issue by jurgob** [volca/markdown-preview#44]
If I put a single # the text is correctly displayed in github but not in the extension.
double # ("##") seems to work right

**Comment by volca** [comment]
Please check [the example](https://raw.githubusercontent.com/volca/markdown-preview/dev/test/test_basic.markdown?refresh). Can you see the right format for single #?

**Comment by jurgob** [comment]
Yes I see it correctly. 
Now I've noticed that the problem is I don t have a whitespace. So 
#Title 
Will not work, but
# Title
Is working.
In github they are both working

**Comment by jurgob** [comment]
Ok, commenting this own post I' ve noticed that #title is not working g neither on github. Sorry for the invalid ticket

**Comment by volca** [comment]
don't worry. So I can close the issue.
