### ISSUE TITLE
math delimiter support depends on headers?

### ISSUE THREAD

**Issue by cben** [volca/markdown-preview#45]
I'm on 0.5.2 from Chrome web store, Chromium 52.0.2743.82, wanted to test math delimeter behavior.
I first tried local file:// which the extension didn't catch (fair enough), then tried a local server and got strange behavior, then discovered same text served online worked fine.

This is the markdown I'm testing: https://gist.github.com/cben/2dd861ac4b5631452fda653275e4a71b

Viewed via [Gist's Raw button](https://gist.githubusercontent.com/cben/2dd861ac4b5631452fda653275e4a71b/raw/9d6159223efde47e5514ff82554a2d36d773f1fa/math.md) nothing renders, I presume because headers don't say it's markdown.
Viewed via [Rawgit](https://rawgit.com/cben/2dd861ac4b5631452fda653275e4a71b/raw/9d6159223efde47e5514ff82554a2d36d773f1fa/math.md) everything works as documented (expected subset with "MathJax" option, all syntaxes with "LaTeX delimiters" option).
But viewed from a local `python3 -m http.serve` server, behaves differently:
- single-backslash `\(inline\) \[display\]` never work
- double-backslash `\\(inline\\) \\[display\\]` only work with "LaTeX delimiters" option (expected "MathJax" to be enough)

I _assume_ header differences somehow cause this?
(Suspected also local http vs https rawgit, but http rawgit also worked fully.)

Here are the headers I see:
Rawgit:

```
< HTTP/2.0 200
< date:Thu, 15 Sep 2016 11:04:12 GMT
< content-type:text/x-markdown;charset=utf-8
< set-cookie:__cfduid=da4f942a74aea0a13ee16830b85eebe401473937451; expires=Fri, 15-Sep-17 11:04:11 GMT; path=/; domain=.rawgit.com; HttpOnly
< x-content-type-options:nosniff
< x-robots-tag:none
< access-control-allow-origin:*
< etag:W/"6bf13333cd1c79ca113e1ff2389cdd60c9f0dedd"
< cache-control:max-age=300
< vary:Accept-Encoding
< rawgit-cache-status:EXPIRED
< server:cloudflare-nginx
< cf-ray:2e2b98af07f0345e-LHR
< 
```

python3 local server:

```
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/3.5.1
< Date: Thu, 15 Sep 2016 11:05:53 GMT
< Content-type: text/markdown
< Content-Length: 466
< Last-Modified: Thu, 15 Sep 2016 10:55:30 GMT
< 
```

**Comment by volca** [comment]
What happened if you rename the file to ```math.txt```  at local server?

**Comment by volca** [comment]
I will reopen the issue if you can repeat it with latest version
