### ISSUE TITLE
Code Syntax Highlighting is now working properly.

### ISSUE THREAD

**Issue by rafpro** [volca/markdown-preview#46]
PHP Code block is not being highlighted anymore for me. I am using local stylesheet to enhance code highlighting. I am working on styling for several days. When I installed this extension for the first time, it was wrapping several elements in the code block. But now I am getting only 'keyword' and number for Languages, and 'attribute' and 'value' for CSS.

Is there any way to make highlight.js work from local filesystem?

Will you please give classes to more language tokens?

**Comment by volca** [comment]
Could you please paste an example? I will test it local.

**Comment by rafpro** [comment]
Thanks for your quick response. I am going to attach screenshots from our demo markdown file preview.

### Java Code Preview Feature Request
![image](https://cloud.githubusercontent.com/assets/5154612/18882593/9c05e24e-8501-11e6-98e6-1728e0824a03.png)

### Plain Preview
![image](https://cloud.githubusercontent.com/assets/5154612/18882623/cba7ee2a-8501-11e6-841a-51477dcd8b83.png)

### PHP Issue with code highlighting
![image](https://cloud.githubusercontent.com/assets/5154612/18882753/5210449e-8502-11e6-839c-98c7b2208a91.png)

@volca your markdown extension is awesome, it must be more enhanced if we would get more code highlighting features such as variables, function name, parameters/arguments, block notation (such as end ... do, parentheses, brackets -- if it's possible - I saw this feature with Prisma). Then definitely we will get more control to showcase our code blocks.

Thanks for not keeping navigation panel as it ruins the clean and simple view of the document.

Thumbs up for your great extension :+1:

**Comment by volca** [comment]
I've uploaded new version plugin to Chrome Store. Let me know if it work.

**Comment by rafpro** [comment]
Thanks a lot @volca, now we are getting more precise targeting options and ability to use existing highlight.js themes! :+1:
