### ISSUE TITLE
无法在高版本的Chrome中工作

### ISSUE THREAD

**Issue by Hourann** [volca/markdown-preview#48]
我的Chrome版本 54.0.2840.71 m (64-bit)，设置页面和右上角图标能正常运行，但是无法解析Markdown文件(.md)，仍然是以普通文本的形式打开。看到插件评论中有一个Chrome版本号是53的同样无法工作。

**Comment by volca** [comment]
请问你有没有在设置界面中，打开"允许访问文件网址"?

![option](https://camo.githubusercontent.com/0947f90b1db6b8f61ccb5d5fde7f7a91c7d97a8c/687474703a2f2f692e696d6775722e636f6d2f717468334b2e706e67)

**Comment by Hourann** [comment]
原来是这个问题，已解决，谢谢！
