### ISSUE TITLE
Whitespace not required in headings

### ISSUE THREAD

**Issue by angea** [volca/markdown-preview#49]
While the [examples](https://help.github.com/articles/basic-writing-and-formatting-syntax/) show a whitespace between the # characters and the headings content, a whitespace is not enforced in practice in the main github viewer (but not in issues text, ironically)

so my [readme](https://raw.githubusercontent.com/corkami/pics/master/README.md) should have his headings displayed correctly.
<img width="669" alt="screen shot 2016-11-30 at 11 58 48" src="https://cloud.githubusercontent.com/assets/5624411/20749876/6d14c908-b6f4-11e6-8b36-2739cc08a0fb.png">
while Markdown preview doesn't display them:
<img width="773" alt="screen shot 2016-11-30 at 11 58 34" src="https://cloud.githubusercontent.com/assets/5624411/20749871/657f51ae-b6f4-11e6-8c0b-10b4abc44d70.png">

**Comment by volca** [comment]
See the issue https://github.com/chjj/marked/issues/201. But I will make a little hack for same behavior with github
