### ISSUE TITLE
Suggestion: Table of Contents

### ISSUE THREAD

**Issue by oldhobbyist** [volca/markdown-preview#51]
May I suggest on automatic table of contents generated from headings.

Thanks.

**Comment by volca** [comment]
Here's a [good start point](https://github.com/chjj/marked/issues/334). Maybe we can add an option for the feature. I will work on this feature when I'm free.

**Comment by Ivorson** [comment]
[Here](https://github.com/Ivorson/markdown-preview) is another option, try it.

**Comment by volca** [comment]
Could you please make a pull request?

Thank you @Ivorson

**Comment by volca** [comment]
see #84 I will make the feature optional
