### ISSUE TITLE
Incorrect math rendering of subscript

### ISSUE THREAD

**Issue by srottschaefer** [volca/markdown-preview#53]
I experienced some very weird math rendering bug of certain constructs containing subscripts (it seems to occur with all math delimiters).

Here are some variations of one construct that renders in some cases and does not with only slight adjustments:

|Input|Renders|Comment|
|------|-----------|--------------|
|`$\frac{w_x}{\sum_z x_z}$` |Yes ||
|`$\frac{w}{\sum_{z} x_z}$` | Yes |
|`$\frac{w_x}{\sum_{z} x_z}$` | No | produces "$\frac{wx}{\sum{z} x_z}$" |
|`$\frac{w\_x}{\sum_{z} x_z}$` | Yes |
|`$\frac{w\_x}{\sum\_{z} x\_z}$` | Yes | escaping all underscores seems to be the safe way |

I would guess the markdown parser messes with the underscores inside math blocks before MathJax is run.
The Chrome console produces no errors so this is not due to an exception.
I don't have time and I am lacking knowledge in JS so I could not investigate further.

**Comment by volca** [comment]
Hi @ktchu do you have any experience about this?

**Comment by r4f** [comment]
An other example is that
x_\gamma = x_i
is rendered correctly, however
x_i = x_\gamma
does not.
Thanks

**Comment by volca** [comment]
I'll reopen the issue if you can repeat it with latest version.
