### ISSUE TITLE
Suggestion / feat reaquest : add optionnal spellchecking on rendered markdown 

### ISSUE THREAD

**Issue by levequej** [volca/markdown-preview#55]
It would be nice to enable spellchecking - maybe faking something like $(markdown_stuff).attr('spellcheck', 'true').attr('contenteditable', 'true')  or any better option.

I know I could have spellchecking in my markdown editor, but chrome integrated one seems to work better + it's cool to be able to have that on a different windows / different screen

**Comment by volca** [comment]
I think It's better that a markdown editor have spellchecking.
