### ISSUE TITLE
Remove 'all website data' permission

### ISSUE THREAD

**Issue by dmurph** [volca/markdown-preview#56]
Hello,

I'd love to use this extension to preview markdown files, but I can't install extensions that can view data on any webpage (especially on my work profile). Can you remove this permission somehow? I just want to view my local markdown files formatted well.

**Comment by volca** [comment]
The warning is caused by "download" permission. Please check this [line](https://github.com/volca/markdown-preview/blob/master/manifest.json#L46). If we don't need the function "Export To HTML" any more, we can delete this line.
