### ISSUE TITLE
Not rendering UTF-8 correctly

### ISSUE THREAD

**Issue by kenfallon** [volca/markdown-preview#57]
The pages are not rendered as utf-8.

As an example add ¥ · £ · € · $ · ¢ · ₡ · ₢ · ₣ · ₤ · ₥ · ₦ · ₧ · ₨ · ₩ · ₪ · ₫ · ₭ · ₮ · ₯ · ₹ to a mark down document and they will be rendered as 
 Â¥ Â· Â£ Â· â‚¬ Â· $ Â· Â¢ Â· â‚¡ Â· â‚¢ Â· â‚£ Â· â‚¤ Â· â‚¥ Â· â‚¦ Â· â‚§ Â· â‚¨ Â· â‚© Â· â‚ª Â· â‚« Â· â‚­ Â· â‚® Â· â‚¯ Â· &#8377

The example is taken from http://kermitproject.org/utf8.html

**Comment by volca** [comment]
Please see #2 and #42
