### ISSUE TITLE
After HTML export no anchor links are working

### ISSUE THREAD

**Issue by jared83** [volca/markdown-preview#58]
Anchor links seem to being converted to absolute paths pointing to an anchor in the md file, rather than regular relative `href="#5"` after the export to HTML (or mhtml actually). Manually editing the links in the output file doesn't help to resolve the issue. Is there a way around this? Currently the Outline becomes useless after the export.
Also, it would be much better if the export to html could export to actual html rather than mhtml.
Best regards
Jared

**Comment by volca** [comment]
see #56 export function is removed
