### ISSUE TITLE
live reload support

### ISSUE THREAD

**Issue by Avinash-Bhat** [volca/markdown-preview#59]
can live reload support be added to this? adding a simple port config and script line in the body of the rendered html should (theoretically) do the trick.

**Comment by volca** [comment]
markdown preview plus support the feature.

**Comment by Avinash-Bhat** [comment]
@volca it has auto-reload (via polling), I am asking about linking it with http://livereload.com/ it should be a trivial process, not to mention that the updates will be almost instantaneous, instead of working to find the optimal reload frequency, reload will work right out of the box.

**Comment by volca** [comment]
It looks great! But it seems not a free software. Is there any free one instead?

**Comment by Avinash-Bhat** [comment]
@volca the livereload is an [opensource software](https://github.com/livereload/LiveReload). It's API is already defined, and integrations with different IDE and editors are already available. 

For example, I use sublime for markdown editing, and it has [packages](https://github.com/alepez/LiveReload-sublimetext3) for the same.

All that has to be done is to add the line `<script src="http://localhost:35729/livereload.js?snipver=1"></script>` inside the generated `<body>` towards the end. Which should be easy enough. 
Now the port and related URL can be made configurable if needed.

**Comment by volca** [comment]
The current auto-reload function can work out of box without any other software or extension. I will not add the livereload feature.
