### ISSUE TITLE
HTML snippets are not rendered

### ISSUE THREAD

**Issue by sujee** [volca/markdown-preview#61]
Env : MPP v 0.5.7, on Chrome on Mac 

The following file is not rendering properly

It actually shows the HTML snippets (<img ...) than rednering.
See image.

here is the md file
```md
<link rel='stylesheet' href='../assets/css/main.css'/>

# heading

<img src="a.png" style="border: 5px solid grey ; max-width:100%;" />
```

Here is the rendering

![image](https://cloud.githubusercontent.com/assets/221159/23776075/d9aa27c2-04e0-11e7-8a0a-9d6ada204a2c.png)

**Comment by sujee** [comment]
after enabling MathJAX the HTML snippets are rendered properly.
is this a regression from #60 ?

**Comment by volca** [comment]
Yes. Do you care about XSS attack? Or we can add an option to allow html content inside markdown

**Comment by sujee** [comment]
1. An option to allow html would be nice

2. Is there a way to sanitize html content?
That allows sane html through?

http://sujee.net (sent from mobile...)

**Comment by eduard-rindt** [comment]
Even when I enable MathJAX, an inlined HTML is not rendered properly.
More precisely, after loading the page, the HTML contents is shown correctly. But just after the 1st auto-reload, all HTML character entities (e.g. &nbsp; or &lt;) reshape back to an appearance exactly as they are written in the page.

**Comment by volca** [comment]
@eduard-rindt Could you please upload an example markdown that I can repeat the issue you said? I tried [this example](https://github.com/volca/markdown-preview/blob/master/test/test_mathjax.markdown) but I can't repeat it.

**Comment by eduard-rindt** [comment]
I do confirm that your update fixed the issue provided that the MathJax gets disabled (and the new HTML content enabled, of course).
With MathJax on, the issue persists.
Check demo files [here](https://drive.google.com/drive/folders/0By7JNXPPP_oZeFd2RWEyVG5UbUU?usp=sharing), please.

**Comment by volca** [comment]
@eduard-rindt sorry. I still can't repeat the issue with your demo md files. 

1. Do you use the latest version markdown preview plus?
2. What's the version of your Chrome?
3. Please take a screenshot about the option page of markdown preview plus

**Comment by eduard-rindt** [comment]
@volca Providing the information:
- Chrome 55.0.2883.87 m
- Markdown Preview Plus 0.5.8
- Options screen:
![image](https://cloud.githubusercontent.com/assets/26387930/23990804/6f87d9fa-0a37-11e7-9bac-5075018e7c0f.png)
