### ISSUE TITLE
Local HTML files are incorrectly rendered in Markdown

### ISSUE THREAD

**Issue by ozmium** [volca/markdown-preview#62]
There is an important bug: If you open a local HTML file on your computer (with extension `*.txt.html` or `*.html`), the Markdown Preview extension will intercept it and treat it as a Markdown file. The URL will start with `file://...`

This happens even if you have **disabled all 8 options in "Supported File Extensions"** and even if you have **disabled "Allow access to file URLs"**.

The only way to stop this bug is to **disable the entire extension**, or use Incognito mode to load the local HTML file.

**Comment by volca** [comment]
I renamed test_basic.markdown to test_basic.html. The issue is not repeated. But test_basic.md.html will
