### ISSUE TITLE
frame/iframe not supported

### ISSUE THREAD

**Issue by zachary-guo** [volca/markdown-preview#67]
When visiting local md file, it works. But I have lots of articles written using markdown, so I write a html page whitch contains two frames, one is to display file tree, another one is to preview md files. But this plugins does not work in frame/iframe(md content is shown directly in the frame rather than rendered in html). The html page like this:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	</head>
	<frameset cols="20%,*" framespacing="0">
		<frame src="tree.html" target="preview" frameborder="no" framespacing="0"></frame>
		<frame name="preview" frameborder="no" framespacing="0"></frame>
	</frameset>
</html>
```

Can author solve this problem?

**Comment by volca** [comment]
Have you checked the option "Enable HTML content"?

see #63 also

**Comment by zachary-guo** [comment]
Yes, I checked it, bit it still does not work in an iframe or  frame.

**Comment by volca** [comment]
The tag iframe is rendered correctly. 

```
<iframe src="https://www.baidu.com">
```

But it can't render tag frame and frameset
