### ISSUE TITLE
Mathjax looks like it is being rendered by CSS/HTML

### ISSUE THREAD

**Issue by HaleTom** [volca/markdown-preview#70]
When a page loads, it first looks like this:

![Incorrect rendering](https://i.imgur.com/kzIjUj9.png)

Then it flashes the correct rendering for about half a second. (The correct renering has different sized brackets. The source is:

```
Cost function of logistic regression (revision):

$$J(\theta) = - \frac{1}{m} \sum_{i=1}^m [ y^{(i)}\ \log (h_\theta (x^{(i)})) + (1 - y^{(i)})\ \log (1 - h_\theta(x^{(i)}))] + \frac{\lambda}{2m}\sum_{j=1}^n \theta_j^2$$

For Neural Networks, it is:

$$ J(\Theta) = - \frac{1}{m} \sum_{i=1}^m \sum_{k=1}^K \left[y^{(i)}_k \log ((h_\Theta (x^{(i)}))_k) + (1 - y^{(i)}_k)\log (1 - (h_\Theta(x^{(i)}))_k)\right] + \frac{\lambda}{2m}\sum_{l=1}^{L-1} \sum_{p=1}^{s_l} \sum_{n=1}^{s_{l+1}} ( \Theta_{n,p}^{(l)})^2$$
```

Then it reverts to the incorrect rendering as displayed above.

I cannot right-click on the formulae to change the Math Renderer - the popup menu is the standard right-click menu rather than the MathJax menu.

**Comment by volca** [comment]
I can't reproduce the issue. Please give more details about:

* what os - windows, linux or macOS
* Chrome version
* Version for markdown preview plus

Thanks

**Comment by HaleTom** [comment]
I'm sorry, it was a cookie issue - the resolution is detailed [here](https://superuser.com/a/1241704/365890).

**Comment by volca** [comment]
Thanks for clear it.
