### ISSUE TITLE
Checkboxes for task list items should be read-only

### ISSUE THREAD

**Issue by haimoz** [volca/markdown-preview#77]
Task list is described here:
https://github.com/blog/1825-task-lists-in-all-markdown-documents

In my opinion, as a static document, the task list items should be read-only.  However, the checkbox used to represent the status of the items are interactive by default.  I would suggest making these checkboxes read-only.

**Comment by volca** [comment]
Thanks. I've merged the pull request to dev branch. I'll push it to Chrome Store ASAP.
