### ISSUE TITLE
GFM Tables not implemented 100%

### ISSUE THREAD

**Issue by nzbart** [volca/markdown-preview#8]
This is definitely the best markdown preview extension for Chrome.

There does appear to be a small bug in Github Flavored Markdown tables. It's probably best to illustrate with a demonstration.

This is the source, with the expected result:
https://gist.github.com/jkschoen/5389209

This is the result rendered in Markdown Preview Plus (if you have it installed):
https://gist.github.com/jkschoen/5389209/raw/184135e166e37efeb482a979508c235ee3c1ca0f/table.md

Note that table rows without pipes on the first line are not rendered as part of the table:

    col 2 is | centered | $12 | zebra stripes | are neat | $1 |

**Comment by volca** [comment]
see #38
