### ISSUE TITLE
`<!-- ... -->`-style comments in markdown should not be shown 

### ISSUE THREAD

**Issue by broofa** [volca/markdown-preview#81]
Per the recent comments in https://gist.github.com/jonikarppinen/47dc8c1d7ab7e911f4c9, `<!-- ... -->` style comments are not rendered in GFM.

**Comment by volca** [comment]
Have you checked the option "Enable HTML content"? I tested the comments and it's commented out right

**Comment by broofa** [comment]
That works... although the warning about XSS attacks is a little scary.  Is that really a concern?  Why would this extension every render unsafe HTML?
