### ISSUE TITLE
"Enable HTML content" should not risk XSS attacks

### ISSUE THREAD

**Issue by broofa** [volca/markdown-preview#82]
![image](https://user-images.githubusercontent.com/164050/33517520-ba66cbd6-d73a-11e7-8f89-4708015ff08c.png)

This warning is scary, but not particularly helpful.  As a user - even as an experienced software/web developer - it's difficult to evalute the risk I may be exposing myself to unless I wade into the code.  Even then, it's dependent on how I have MDP configured, and my usage patterns. 

IMHO, this feature should either be removed entirely, or fixed to remove the XSS risk.  To that end, it looks like https://www.npmjs.com/package/sanitize-html is pretty popular and comes with a decent set of defaults.

**Comment by volca** [comment]
Please see this issue #60. The sanitize option make the content confuse and it's unreadable.

**Comment by broofa** [comment]
Okay, I've read through #60 and related comments.  If I'm reading this right, sanitization is enabled by default due to the CVE mentioned in that issue, and only turned off when `mathJax` is enabled.  I think there are a couple problems here.

First, equations/MathJax are not part of the core MarkDown specs (CommonMark or GFM). [HTML blocks](http://spec.commonmark.org/0.28/#html-block), however, are part of the core specs.  The default behavior should prefer support for core features over non-standard features.  IMHO.

That said, Github only supports a subset of HTML Blocks. I believe the sanitize `<script>` and `<style>` blocks, probably due to XSS concerns.  I would suggest mimic'ing their behavior in this regard since I imagine the majority of users of this extension are using it to preview Github content.

Second, I don't see this as a problem of whether or not sanitization should be enabled.  It should *always* be on because it provides an important security measure. Rather, it's a question of what the sanitization rules should be.  E.g. There's really no reason why `<b>Hello</b>` should be sanitized (as it currently is with MDP's default settings ☹️).

If MathJax requires disabling sanitization rules that prevent XSS attacks then *that* is where the XSS warning should be.  On the option to enable MathJax.  And, if enabled, it shouldn't disable sanitization but, rather, switch to a more liberal of sanitization rules that work for MathJax, while still 1) preventing XSS, and 2) allowing basic HTML blocks to continue to work (to whatever degree is possible).

(Note: Depending on how many people actually use the MathJax/LaTeX support, I would argue that these features should be offered in a different extension, forked from this one. "MarkDown Preview Math" or something.)
