### ISSUE TITLE
Odd problem with header rendering

### ISSUE THREAD

**Issue by nightrune** [volca/markdown-preview#86]
I had a document with the markdown 

```
### Theme
```

and it looked like it broke css rendering. It was all flat text but bold and items still worked. Rendering works if I just change the tag to 

```
### Themer
```

or 

```
### Themes
````

Tested in Chrome Version 65.0.3325.181 (Official Build), Have Markdown preview plus Version: 0.6.5

Both cases the file is on a local drive with chrome given permissions to view the file.

Broken Case - https://gist.github.com/nightrune/8723f9401db0dc404495b11f00c14f24
Working Case - https://gist.github.com/nightrune/14f12acade551ce8dccd23f6de959681

Sometimes it'll look like it renders ok, but if you refresh the page it'll break rendering. The text will still be bold and html seems fine with li elements, but css itself seems broken some how.

**Comment by volca** [comment]
I can't re-produce the issue. My chrome is Version 67.0.3396.99 (Official Build) (64-bit)
