### ISSUE TITLE
link to #header-two does not jump to corresponding header

### ISSUE THREAD

**Issue by andrew-proper** [volca/markdown-preview#88]
I would like to be able to use links like the following with this extension, and have the page jump down to the corresponding header. I see that the <h> tags have `id="value"` attributes, but it does not work to jump to them. Maybe this is because the HTML is rendered by the extension after the page loads. 

Could the extension be updated to jump down to the `<h>` tag twith the targeted `id` attribute?

For example:

my-file.md#header-two

I would like it to jump to `#header-two`

if the markdown was:

``` markdown
# header-one

content

# header-two

content
```

**Comment by volca** [comment]
Please try v0.6.7 instead

**Comment by m2acgi** [comment]
I refer to https://gist.github.com/asabaylus/3071099 to set the anchor, but it doesn't work in the **markdown preview**.
