### ISSUE TITLE
Open *.md will downlord rather than preview

### ISSUE THREAD

**Issue by xiekeyi98** [volca/markdown-preview#93]
Chrome Version: Chrome 69
I have three computers and only one has the problem.

When I open the : Access the file URL and all other permissions, but when I open the filename.md , Chrome will download it rather than preview it .
If I change the name to filename.txt , and it will preview perfectly.

Anyone meet this problem ?

Thanks a lot .

**Comment by xiekeyi98** [comment]
The Chinese only the translation for upon

刚刚发现项目中似乎有用汉语的commit提交痕迹，那我还是用汉语再复述一下问题吧（英语太差了）。

我有三台电脑，都是chrome 69.
其中一台安装后，打开md后缀名会变成下载（把md改成txt，可以正常渲染)。
搜索引擎了一下，参考了chrome打开html变下载的问题，打开pdf变下载的问题，并没有解决。
删除浏览记录 重置chrome恢复默认设置，重启电脑均不能奏效。
请问这个问题是什么？（插件正常启用，也打开了访问文件URL选项）

**Comment by volca** [comment]
I just tested with Chrome Version 69.0.3497.100 (macOS) and it works fine.

* Did you access a local md file?
* Do you use windows or ubuntu?

**Comment by xiekeyi98** [comment]
Thinks a lot . 
I use Windows 10(1803) , and definitely allow chrome access my local md file(I also test cancel it and allow it again , but it does not work ).

I find some similiar questions in the [plugin sites](https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl)
such as : 
![image](https://user-images.githubusercontent.com/7782671/46186893-92d49380-c313-11e8-9cbf-aab5f566c665.png)

And I can not find solution in the site.

What can I do for you so that you could find why it could not work correctly?

**Comment by volca** [comment]
I also tried with chrome 69.0 on windows 10(1803) and it also works fine. Please tried the steps:

* Open url chrome://extensions
* Disable the extension "Markdown Preview Plus"
* Open your local md file with chrome and check the behavior

I can open a plain md file with chrome if I disabled the extension.

**Comment by xiekeyi98** [comment]
It also can not work correctly. ( I have changed the Chrome all to the default)

![test](https://user-images.githubusercontent.com/7782671/46198356-e01a2a80-c33e-11e8-84d3-8d599d5a82bf.gif)

**Comment by volca** [comment]
That's very strange. I can't reproduce the issue. Please also try other file extension such as `rmd`, `markdown` or `text`

**Comment by xiekeyi98** [comment]
Sigh , maybe I can use `md` anymore .
All in all , please accept my thanks for you .
