### ISSUE TITLE
请求添加一个选择MathJax/Katex渲染Latex公式的选项

### ISSUE THREAD

**Issue by CFWLoader** [volca/markdown-preview#94]
MathJax中的换行是两个反斜杠，Katex用的三反斜杠换行。在更新0.71前一直用的MathJax的双反斜杠，近期打开之前编写的文档发现只要涉及使用换行的latex公式渲染都崩了，找了一下发现是插件从MathJax换成了Katex，请求作者在未来更新时提供一个选择latex渲染引擎的选项。

**Comment by zgce** [comment]
我提交了个PR[ #100](https://github.com/volca/markdown-preview/pull/100)看是否能解决您的问题

**Comment by volca** [comment]
Thanks @zgce 

I closed the issue. You can reopen it if the PR #100 not work.
